image: node:16.13-alpine3.14

stages:
  - dependencies
  - lint
  - test
  - build
  - plan-deploy
  - deploy

cache:
  paths:
    - node_modules/

install_dependencies:
  stage: dependencies
  script:
    - yarn install
  artifacts:
    paths:
      - node_modules
    expire_in: 20 minutes
  allow_failure: false

lint_code:
  stage: lint
  script: 
    - yarn lint:ci
  allow_failure: false

lint_deploy_script:
  stage: lint
  image:
    name: google/cloud-sdk:alpine
  before_script:
    - apk add terraform
    - cd deploy/gcp
    - echo $GCP_KEY | base64 -d > ./antoineamaradev.json
    - terraform init
  script:
    - terraform validate
  allow_failure: false

testing:
  stage: test
  script: yarn test
  allow_failure: false

build_website:
  stage: build
  script:
    - yarn build
  artifacts:
    paths:
      - ./dist/
    expire_in: 20 minutes
  allow_failure: false
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
    - if: $CI_COMMIT_TAG

terraform_plan:
  stage: plan-deploy
  image:
    name: google/cloud-sdk:alpine
  before_script:
    - apk add terraform
    - cd deploy/gcp/
    - echo $GCP_KEY | base64 -d > ./antoineamaradev.json
    - terraform init
  script:
    - terraform plan -out "../../deployment_plan"
  artifacts:
    paths:
      - deployment_plan
  allow_failure: false
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
      when: manual
    - if: $CI_COMMIT_TAG

terraform_apply:
  stage: deploy
  image:
    name: google/cloud-sdk:alpine
  before_script:
    - apk add terraform zip jq
    - cd deploy/gcp
    - echo $GCP_KEY | base64 -d > ./antoineamaradev.json
    - terraform init -input=false
    - zip -r -j /tmp/submit-contact-form.zip ../../functions/contact-form/
    - zip -r -j /tmp/get-github-profile.zip ../../functions/get-github-profile/
  script:
    - terraform apply -input=false ../../deployment_plan
    - "terraform output --json | jq '.get_blog_posts_https_url = .get_blog_posts_https_url.value | .get_github_profile_https_url = .get_github_profile_https_url.value | .submit_contact_form_https_url = .submit_contact_form_https_url.value | del('.website_configurations') | del('.website_ip') | del('.website_domain_name')' > api-urls.json"
    - gcloud auth activate-service-account --key-file $TF_VAR_authkey
    - gsutil cp -r api-urls.json "gs://$TF_VAR_domain/configs/api-urls.json"
  allow_failure: false
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
      when: manual
    - if: $CI_COMMIT_TAG

terraform_destroy:
  stage: deploy
  image:
    name: google/cloud-sdk:alpine
  before_script:
    - apk add terraform
    - cd deploy/gcp
    - echo $GCP_KEY | base64 -d > ./antoineamaradev.json
    - terraform init -input=false
  script:
    - terraform destroy -auto-approve
  allow_failure: false
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
      when: manual
    - if: $CI_COMMIT_TAG
      when: manual
