version: "3"

services:
  reverse-proxy:
    image: traefik:v2.3
    command:
      - --api.insecure=true
      - --entrypoints.web.address=:80
      - --entrypoints.web.http.redirections.entryPoint.to=webs
      - --entrypoints.web.http.redirections.entryPoint.scheme=https
      - --entrypoints.webs.address=:443 #Declares the web-secure entrypoint in Traefik
      - --providers.docker
      - --providers.file.directory=/configuration/
      - --providers.file.watch=true
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    networks:
      - public
      - webservices
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./Docker/traefik/ssl:/etc/cert/
      - ./Docker/traefik/configuration/:/configuration/
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.proxy.service=proxy"
      - "traefik.http.routers.proxy.rule=Host(`proxy.localhost`)"
      - "traefik.http.services.proxy.loadbalancer.server.port=8080"
      - "traefik.http.routers.proxy.tls=true"
  website:
    image: staticpack-nodejs-yarn
    build:
      context: ./Docker/node
    volumes:
      - ./:/workspace/
    working_dir: /workspace/
    networks:
      - webservices
    environment:
      - NODE_ENV=development
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.website.service=website"
      - "traefik.http.routers.website.rule=Host(`antoine.dev.localhost`)"
      - "traefik.http.services.website.loadbalancer.server.port=9000"
      - "traefik.http.routers.website.tls=true"
    command: yarn serve:dev
  faas:
    image: nodejs-yarn
    build:
      context: ./Docker/node
    volumes:
      - ./functions/:/workspace/
    working_dir: /workspace/
    networks:
      - public
      - webservices
    ports:
      - "9042:9042"
    environment:
      - NODE_ENV=development
      - PORT=3000
      - GITHUB_TOKEN=4242424242442
      - SMTP_USERNAME=antoine.dev.localhost
      - SMTP_PASSWORD=paulo2019
      - SMTP_HOST=mailhog
      - SMTP_PORT=1025
      - SMTP_MAIL_SENDER=no-reply@antoineamara.dev
      - SMTP_DEST_MAIL=contact@antoineamara.dev
      - AUTHORIZED_ORIGINS=https://antoine.dev.localhost,https://www.antoine.dev.localhost
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.faas.service=faas"
      - "traefik.http.routers.faas.rule=Host(`north-fr-antoinedev.cloudfunction.localhost`)"
      - "traefik.http.services.faas.loadbalancer.server.port=3000"
      - "traefik.http.routers.faas.tls=true"
    command: yarn serve
  mailhog:
    image: mailhog/mailhog:v1.0.0
    volumes: 
      - ./Docker/mailbox/:/maildir/
    networks: 
      - webservices
    expose:
      - 1025
      - 8025
    environment:
      - MH_STORAGE=maildir
      - MH_MAILDIR_PATH=/maildir/
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mailbox.service=mailbox"
      - "traefik.http.routers.mailbox.rule=Host(`mailbox.antoinedev.localhost`)"
      - "traefik.http.services.mailbox.loadbalancer.server.port=8025"
      - "traefik.http.routers.mailbox.tls=true"

networks:
  public:
  webservices:
