module.exports = {
  blogposts: [
    {
      type_of: 'article',
      id: 586511,
      title: 'Understanding the difference between where and select in Rails',
      description: 'In my previous post, I talked about how to solve the N+1 query problem in Rails to improve the perf...',
      readable_publish_date: 'Mar  1',
      slug: 'understanding-the-difference-between-where-and-select-in-rails-655',
      path: '/junko911/understanding-the-difference-between-where-and-select-in-rails-655',
      url: 'https://dev.to/junko911/understanding-the-difference-between-where-and-select-in-rails-655',
      comments_count: 0,
      public_reactions_count: 10,
      collection_id: null,
      published_timestamp: '2021-03-01T16:10:47Z',
      positive_reactions_count: 10,
      cover_image: null,
      social_image: 'https://dev.to/social_previews/article/586511.png',
      canonical_url: 'https://dev.to/junko911/understanding-the-difference-between-where-and-select-in-rails-655',
      created_at: '2021-01-29T21:33:08Z',
      edited_at: '2021-03-01T23:48:37Z',
      crossposted_at: null,
      published_at: '2021-03-01T16:10:47Z',
      last_comment_at: '2021-03-01T16:10:47Z',
      tag_list: [
        'rails',
        'sql',
        'performance',
        'beginners'
      ],
      tags: 'rails, sql, performance, beginners',
      user: {
        name: 'Junko T.',
        username: 'junko911',
        twitter_username: null,
        github_username: 'junko911',
        website_url: null,
        profile_image: 'https://res.cloudinary.com/practicaldev/image/fetch/s--WNueTQkE--/c_fill,f_auto,fl_progressive,h_640,q_auto,w_640/https://dev-to-uploads.s3.amazonaws.com/uploads/user/profile_image/504532/89c4467b-885f-40e2-9c68-ddaf9a69fd69.jpeg',
        profile_image_90: 'https://res.cloudinary.com/practicaldev/image/fetch/s--4gqmleTo--/c_fill,f_auto,fl_progressive,h_90,q_auto,w_90/https://dev-to-uploads.s3.amazonaws.com/uploads/user/profile_image/504532/89c4467b-885f-40e2-9c68-ddaf9a69fd69.jpeg'
      }
    },
    {
      type_of: 'article',
      id: 621680,
      title: 'Diagnosing Performance Issues',
      description: "Once you've determined you need to improve your site performance, how do you do that?",
      readable_publish_date: 'Mar  1',
      slug: 'diagnosing-performance-issues-3k5j',
      path: '/laurieontech/diagnosing-performance-issues-3k5j',
      url: 'https://dev.to/laurieontech/diagnosing-performance-issues-3k5j',
      comments_count: 4,
      public_reactions_count: 77,
      collection_id: null,
      published_timestamp: '2021-03-01T14:40:00Z',
      positive_reactions_count: 77,
      cover_image: 'https://res.cloudinary.com/practicaldev/image/fetch/s--sceCPlsP--/c_imagga_scale,f_auto,fl_progressive,h_420,q_auto,w_1000/https://dev-to-uploads.s3.amazonaws.com/uploads/articles/knmh8o39vk548ax67atw.jpeg',
      social_image: 'https://res.cloudinary.com/practicaldev/image/fetch/s--EoUgqEQf--/c_imagga_scale,f_auto,fl_progressive,h_500,q_auto,w_1000/https://dev-to-uploads.s3.amazonaws.com/uploads/articles/knmh8o39vk548ax67atw.jpeg',
      canonical_url: 'https://laurieontech.com/posts/performance-diagnosis/',
      created_at: '2021-03-01T14:37:06Z',
      edited_at: null,
      crossposted_at: null,
      published_at: '2021-03-01T14:40:00Z',
      last_comment_at: '2021-03-02T05:40:50Z',
      tag_list: [
        'webdev',
        'javascript',
        'productivity',
        'beginners'
      ],
      tags: 'webdev, javascript, productivity, beginners',
      user: {
        name: 'Laurie',
        username: 'laurieontech',
        twitter_username: 'laurieontech',
        github_username: null,
        website_url: 'http://laurieontech.com',
        profile_image: 'https://res.cloudinary.com/practicaldev/image/fetch/s--bDPRyElD--/c_fill,f_auto,fl_progressive,h_640,q_auto,w_640/https://dev-to-uploads.s3.amazonaws.com/uploads/user/profile_image/67245/e491c3cb-9cae-4f54-9a6e-79cbd28eea4f.jpeg',
        profile_image_90: 'https://res.cloudinary.com/practicaldev/image/fetch/s--TjzK_VGC--/c_fill,f_auto,fl_progressive,h_90,q_auto,w_90/https://dev-to-uploads.s3.amazonaws.com/uploads/user/profile_image/67245/e491c3cb-9cae-4f54-9a6e-79cbd28eea4f.jpeg'
      }
    },
    {
      type_of: 'article',
      id: 620738,
      title: 'How to Practice for Code Challenges',
      description: 'Introduction    You are given coins of different values and a total amount of money amount....',
      readable_publish_date: 'Mar  1',
      slug: 'how-to-practice-for-code-challenges-4gbc',
      path: '/mikechrupcala/how-to-practice-for-code-challenges-4gbc',
      url: 'https://dev.to/mikechrupcala/how-to-practice-for-code-challenges-4gbc',
      comments_count: 4,
      public_reactions_count: 64,
      collection_id: null,
      published_timestamp: '2021-03-01T14:02:06Z',
      positive_reactions_count: 64,
      cover_image: 'https://res.cloudinary.com/practicaldev/image/fetch/s--tl8MlHo1--/c_imagga_scale,f_auto,fl_progressive,h_420,q_auto,w_1000/https://dev-to-uploads.s3.amazonaws.com/uploads/articles/k8vmzxc9ztaktef5ywfe.png',
      social_image: 'https://res.cloudinary.com/practicaldev/image/fetch/s--0Qz-wuYD--/c_imagga_scale,f_auto,fl_progressive,h_500,q_auto,w_1000/https://dev-to-uploads.s3.amazonaws.com/uploads/articles/k8vmzxc9ztaktef5ywfe.png',
      canonical_url: 'https://dev.to/mikechrupcala/how-to-practice-for-code-challenges-4gbc',
      created_at: '2021-02-28T15:20:16Z',
      edited_at: null,
      crossposted_at: null,
      published_at: '2021-03-01T14:02:06Z',
      last_comment_at: '2021-03-02T11:28:36Z',
      tag_list: [
        'webdev',
        'beginners',
        'career',
        'javascript'
      ],
      tags: 'webdev, beginners, career, javascript',
      user: {
        name: 'Michael Chrupcala',
        username: 'mikechrupcala',
        twitter_username: 'mikechrupcala',
        github_username: null,
        website_url: null,
        profile_image: 'https://res.cloudinary.com/practicaldev/image/fetch/s--4B0cJLqZ--/c_fill,f_auto,fl_progressive,h_640,q_auto,w_640/https://dev-to-uploads.s3.amazonaws.com/uploads/user/profile_image/571164/77287f2c-35a6-495e-a695-086401dd008d.jpg',
        profile_image_90: 'https://res.cloudinary.com/practicaldev/image/fetch/s--XRrcCs1x--/c_fill,f_auto,fl_progressive,h_90,q_auto,w_90/https://dev-to-uploads.s3.amazonaws.com/uploads/user/profile_image/571164/77287f2c-35a6-495e-a695-086401dd008d.jpg'
      }
    },
    {
      type_of: 'article',
      id: 573403,
      title: 'CSS in 3D: Learning to think in Cubes Instead of Boxes',
      description: 'My path to learning CSS was a little unorthodox. I didn’t start as a front-end developer. I was a Jav...',
      readable_publish_date: 'Mar  1',
      slug: 'css-in-3d-learning-to-think-in-cubes-instead-of-boxes-4ank',
      path: '/jh3y/css-in-3d-learning-to-think-in-cubes-instead-of-boxes-4ank',
      url: 'https://dev.to/jh3y/css-in-3d-learning-to-think-in-cubes-instead-of-boxes-4ank',
      comments_count: 1,
      public_reactions_count: 54,
      collection_id: null,
      published_timestamp: '2021-03-01T16:37:35Z',
      positive_reactions_count: 54,
      cover_image: 'https://res.cloudinary.com/practicaldev/image/fetch/s--IgHc-uq8--/c_imagga_scale,f_auto,fl_progressive,h_420,q_auto,w_1000/https://dev-to-uploads.s3.amazonaws.com/uploads/articles/66fxlqupwjw62m2xkjem.jpg',
      social_image: 'https://res.cloudinary.com/practicaldev/image/fetch/s--cVQ5QCCp--/c_imagga_scale,f_auto,fl_progressive,h_500,q_auto,w_1000/https://dev-to-uploads.s3.amazonaws.com/uploads/articles/66fxlqupwjw62m2xkjem.jpg',
      canonical_url: 'https://jhey.dev/writing/css-in-3d-learning-to-think-in-cubes-instead-of-boxes/',
      created_at: '2021-01-16T15:07:52Z',
      edited_at: null,
      crossposted_at: '2021-03-01T16:37:35Z',
      published_at: '2021-03-01T16:37:35Z',
      last_comment_at: '2021-03-01T17:02:20Z',
      tag_list: [
        'css',
        'tutorial',
        'webdev',
        'design'
      ],
      tags: 'css, tutorial, webdev, design',
      user: {
        name: 'Jhey Tompkins',
        username: 'jh3y',
        twitter_username: 'jh3yy',
        github_username: 'jh3y',
        website_url: 'https://jhey.dev',
        profile_image: 'https://res.cloudinary.com/practicaldev/image/fetch/s--vqtDSO_O--/c_fill,f_auto,fl_progressive,h_640,q_auto,w_640/https://dev-to-uploads.s3.amazonaws.com/uploads/user/profile_image/288872/9f557ca6-9b98-4a65-87c5-ca8eee1028d3.jpg',
        profile_image_90: 'https://res.cloudinary.com/practicaldev/image/fetch/s--DJmuW5UC--/c_fill,f_auto,fl_progressive,h_90,q_auto,w_90/https://dev-to-uploads.s3.amazonaws.com/uploads/user/profile_image/288872/9f557ca6-9b98-4a65-87c5-ca8eee1028d3.jpg'
      }
    },
    {
      type_of: 'article',
      id: 620668,
      title: 'Six tips to improve your code review skills',
      description: 'In my opinion, code review is one of the most effective tools for improving the code base and alignin...',
      readable_publish_date: 'Mar  1',
      slug: 'six-tips-to-improve-your-code-review-skills-95a',
      path: '/n_tepluhina/six-tips-to-improve-your-code-review-skills-95a',
      url: 'https://dev.to/n_tepluhina/six-tips-to-improve-your-code-review-skills-95a',
      comments_count: 1,
      public_reactions_count: 45,
      collection_id: null,
      published_timestamp: '2021-03-01T14:23:22Z',
      positive_reactions_count: 45,
      cover_image: 'https://res.cloudinary.com/practicaldev/image/fetch/s--U0h0POU---/c_imagga_scale,f_auto,fl_progressive,h_420,q_auto,w_1000/https://dev-to-uploads.s3.amazonaws.com/uploads/articles/3b5zibkj7l8sxaseppp2.jpeg',
      social_image: 'https://res.cloudinary.com/practicaldev/image/fetch/s--XqXuD0pC--/c_imagga_scale,f_auto,fl_progressive,h_500,q_auto,w_1000/https://dev-to-uploads.s3.amazonaws.com/uploads/articles/3b5zibkj7l8sxaseppp2.jpeg',
      canonical_url: 'https://dev.to/n_tepluhina/six-tips-to-improve-your-code-review-skills-95a',
      created_at: '2021-02-28T13:22:24Z',
      edited_at: null,
      crossposted_at: null,
      published_at: '2021-03-01T14:23:22Z',
      last_comment_at: '2021-03-02T06:46:11Z',
      tag_list: [],
      tags: '',
      user: {
        name: 'Natalia Tepluhina',
        username: 'n_tepluhina',
        twitter_username: 'N_Tepluhina',
        github_username: 'NataliaTepluhina',
        website_url: null,
        profile_image: 'https://res.cloudinary.com/practicaldev/image/fetch/s--iyL8Acbw--/c_fill,f_auto,fl_progressive,h_640,q_auto,w_640/https://dev-to-uploads.s3.amazonaws.com/uploads/user/profile_image/84354/53a269f0-793d-4d4a-b7d5-12e7fcdac0ea.jpg',
        profile_image_90: 'https://res.cloudinary.com/practicaldev/image/fetch/s--_x31hUz1--/c_fill,f_auto,fl_progressive,h_90,q_auto,w_90/https://dev-to-uploads.s3.amazonaws.com/uploads/user/profile_image/84354/53a269f0-793d-4d4a-b7d5-12e7fcdac0ea.jpg'
      }
    },
    {
      type_of: 'article',
      id: 621593,
      title: 'Detailed Explanation of CSS Position Property',
      description: 'There are two important types of properties you need to know about when positioning elements on a scr...',
      readable_publish_date: 'Mar  1',
      slug: 'detailed-explanation-of-css-position-property-1c8c',
      path: '/lindaojo/detailed-explanation-of-css-position-property-1c8c',
      url: 'https://dev.to/lindaojo/detailed-explanation-of-css-position-property-1c8c',
      comments_count: 1,
      public_reactions_count: 50,
      collection_id: null,
      published_timestamp: '2021-03-01T13:11:54Z',
      positive_reactions_count: 50,
      cover_image: 'https://res.cloudinary.com/practicaldev/image/fetch/s--8sPCu2QJ--/c_imagga_scale,f_auto,fl_progressive,h_420,q_auto,w_1000/https://dev-to-uploads.s3.amazonaws.com/uploads/articles/k0gs71vlv0d7mb3d3ief.png',
      social_image: 'https://res.cloudinary.com/practicaldev/image/fetch/s--2EKHMqn7--/c_imagga_scale,f_auto,fl_progressive,h_500,q_auto,w_1000/https://dev-to-uploads.s3.amazonaws.com/uploads/articles/k0gs71vlv0d7mb3d3ief.png',
      canonical_url: 'https://dev.to/lindaojo/detailed-explanation-of-css-position-property-1c8c',
      created_at: '2021-03-01T13:11:54Z',
      edited_at: null,
      crossposted_at: null,
      published_at: '2021-03-01T13:11:54Z',
      last_comment_at: '2021-03-02T12:01:03Z',
      tag_list: [
        'css',
        'webdev',
        'beginners',
        'programming'
      ],
      tags: 'css, webdev, beginners, programming',
      user: {
        name: 'Linda',
        username: 'lindaojo',
        twitter_username: 'LindaOjo_',
        github_username: null,
        website_url: 'https://lindaojo.com',
        profile_image: 'https://res.cloudinary.com/practicaldev/image/fetch/s--tx04esSd--/c_fill,f_auto,fl_progressive,h_640,q_auto,w_640/https://dev-to-uploads.s3.amazonaws.com/uploads/user/profile_image/478418/ded3eb2a-a8e0-42ad-8c10-997e41d33c90.jpg',
        profile_image_90: 'https://res.cloudinary.com/practicaldev/image/fetch/s--QDPbmrbZ--/c_fill,f_auto,fl_progressive,h_90,q_auto,w_90/https://dev-to-uploads.s3.amazonaws.com/uploads/user/profile_image/478418/ded3eb2a-a8e0-42ad-8c10-997e41d33c90.jpg'
      }
    },
    {
      type_of: 'article',
      id: 601284,
      title: 'Learning JavaScript Promises',
      description: 'Hello, I am going to give you a quick introduction about JavaScript promises and why they work the wa...',
      readable_publish_date: 'Mar  1',
      slug: 'learning-javascript-promises-2dep',
      path: '/marlonry/learning-javascript-promises-2dep',
      url: 'https://dev.to/marlonry/learning-javascript-promises-2dep',
      comments_count: 0,
      public_reactions_count: 49,
      collection_id: null,
      published_timestamp: '2021-03-01T10:30:33Z',
      positive_reactions_count: 49,
      cover_image: 'https://res.cloudinary.com/practicaldev/image/fetch/s--ohSq_ZIe--/c_imagga_scale,f_auto,fl_progressive,h_420,q_auto,w_1000/https://dev-to-uploads.s3.amazonaws.com/i/cfldt7co764tq8m5djca.png',
      social_image: 'https://res.cloudinary.com/practicaldev/image/fetch/s--VuUnFjse--/c_imagga_scale,f_auto,fl_progressive,h_500,q_auto,w_1000/https://dev-to-uploads.s3.amazonaws.com/i/cfldt7co764tq8m5djca.png',
      canonical_url: 'https://dev.to/marlonry/learning-javascript-promises-2dep',
      created_at: '2021-02-12T07:28:41Z',
      edited_at: null,
      crossposted_at: null,
      published_at: '2021-03-01T10:30:33Z',
      last_comment_at: '2021-03-01T10:30:33Z',
      tag_list: [
        'todayilearned',
        'javascript',
        'react',
        'beginners'
      ],
      tags: 'todayilearned, javascript, react, beginners',
      user: {
        name: 'marlonry',
        username: 'marlonry',
        twitter_username: null,
        github_username: 'marlonry',
        website_url: null,
        profile_image: 'https://res.cloudinary.com/practicaldev/image/fetch/s--t3lJ-KSC--/c_fill,f_auto,fl_progressive,h_640,q_auto,w_640/https://dev-to-uploads.s3.amazonaws.com/uploads/user/profile_image/509388/5f0be121-ed1f-4b69-b74c-5e3132011236.jpg',
        profile_image_90: 'https://res.cloudinary.com/practicaldev/image/fetch/s--e522uJ6H--/c_fill,f_auto,fl_progressive,h_90,q_auto,w_90/https://dev-to-uploads.s3.amazonaws.com/uploads/user/profile_image/509388/5f0be121-ed1f-4b69-b74c-5e3132011236.jpg'
      },
      flare_tag: {
        name: 'todayilearned',
        bg_color_hex: '#ffedc9',
        text_color_hex: '#820000'
      }
    },
    {
      type_of: 'article',
      id: 617245,
      title: 'How To Create A Global "JSON Search Algorithm" In JavaScript.',
      description: 'Writing a Search feature for every single page or section on your website can be really tedious, and...',
      readable_publish_date: 'Mar  1',
      slug: 'how-to-create-a-global-json-search-algorithm-in-javascript-55ko',
      path: '/emmaccen/how-to-create-a-global-json-search-algorithm-in-javascript-55ko',
      url: 'https://dev.to/emmaccen/how-to-create-a-global-json-search-algorithm-in-javascript-55ko',
      comments_count: 6,
      public_reactions_count: 38,
      collection_id: null,
      published_timestamp: '2021-03-01T10:24:34Z',
      positive_reactions_count: 38,
      cover_image: 'https://res.cloudinary.com/practicaldev/image/fetch/s--uqaE7mpc--/c_imagga_scale,f_auto,fl_progressive,h_420,q_auto,w_1000/https://dev-to-uploads.s3.amazonaws.com/uploads/articles/v6uj08lrfzlkoor0wz5s.png',
      social_image: 'https://res.cloudinary.com/practicaldev/image/fetch/s--ptdFxi6a--/c_imagga_scale,f_auto,fl_progressive,h_500,q_auto,w_1000/https://dev-to-uploads.s3.amazonaws.com/uploads/articles/v6uj08lrfzlkoor0wz5s.png',
      canonical_url: 'https://dev.to/emmaccen/how-to-create-a-global-json-search-algorithm-in-javascript-55ko',
      created_at: '2021-02-24T20:05:25Z',
      edited_at: null,
      crossposted_at: null,
      published_at: '2021-03-01T10:24:34Z',
      last_comment_at: '2021-03-02T09:14:19Z',
      tag_list: [
        'javascript',
        'webdev',
        'algorithms'
      ],
      tags: 'javascript, webdev, algorithms',
      user: {
        name: 'Lucius Emmanuel Emmaccen',
        username: 'emmaccen',
        twitter_username: 'Emmaccen',
        github_username: 'Emmaccen',
        website_url: 'https://emmaccen.netlify.app/',
        profile_image: 'https://res.cloudinary.com/practicaldev/image/fetch/s--SUDjMvOp--/c_fill,f_auto,fl_progressive,h_640,q_auto,w_640/https://dev-to-uploads.s3.amazonaws.com/uploads/user/profile_image/372534/450e41d1-63dc-4a79-adf9-3bd1abb70f49.jpg',
        profile_image_90: 'https://res.cloudinary.com/practicaldev/image/fetch/s--fnOLwP2s--/c_fill,f_auto,fl_progressive,h_90,q_auto,w_90/https://dev-to-uploads.s3.amazonaws.com/uploads/user/profile_image/372534/450e41d1-63dc-4a79-adf9-3bd1abb70f49.jpg'
      }
    },
    {
      type_of: 'article',
      id: 621510,
      title: 'Remote Development in Visual Studio Code',
      description: 'Introduction   If you run multiple servers and you do not want to edit files and open folder...',
      readable_publish_date: 'Mar  1',
      slug: 'remote-development-in-visual-studio-code-4i4b',
      path: '/alexgeorgiev17/remote-development-in-visual-studio-code-4i4b',
      url: 'https://dev.to/alexgeorgiev17/remote-development-in-visual-studio-code-4i4b',
      comments_count: 4,
      public_reactions_count: 21,
      collection_id: null,
      published_timestamp: '2021-03-01T10:52:56Z',
      positive_reactions_count: 21,
      cover_image: 'https://res.cloudinary.com/practicaldev/image/fetch/s--fOlp0y_7--/c_imagga_scale,f_auto,fl_progressive,h_420,q_auto,w_1000/https://dev-to-uploads.s3.amazonaws.com/uploads/articles/lxsj68hcv67ww2tb84p4.png',
      social_image: 'https://res.cloudinary.com/practicaldev/image/fetch/s--osIKideK--/c_imagga_scale,f_auto,fl_progressive,h_500,q_auto,w_1000/https://dev-to-uploads.s3.amazonaws.com/uploads/articles/lxsj68hcv67ww2tb84p4.png',
      canonical_url: 'https://devdojo.com/alexg/remote-development-in-visual-studio',
      created_at: '2021-03-01T10:46:56Z',
      edited_at: null,
      crossposted_at: '2021-03-01T10:52:56Z',
      published_at: '2021-03-01T10:52:56Z',
      last_comment_at: '2021-03-02T07:52:53Z',
      tag_list: [
        'linux',
        'devops',
        'visualstudio',
        'beginners'
      ],
      tags: 'linux, devops, visualstudio, beginners',
      user: {
        name: 'Alex Georgiev',
        username: 'alexgeorgiev17',
        twitter_username: 'AlexGeorgiev17',
        github_username: 'GeorgievAlex',
        website_url: 'https://alexgeorgiev.net',
        profile_image: 'https://res.cloudinary.com/practicaldev/image/fetch/s--e_q_ERiK--/c_fill,f_auto,fl_progressive,h_640,q_auto,w_640/https://dev-to-uploads.s3.amazonaws.com/uploads/user/profile_image/374570/7cadeb54-a2f5-4d1a-a70f-be3583e3937c.jpg',
        profile_image_90: 'https://res.cloudinary.com/practicaldev/image/fetch/s--B0VKU-xi--/c_fill,f_auto,fl_progressive,h_90,q_auto,w_90/https://dev-to-uploads.s3.amazonaws.com/uploads/user/profile_image/374570/7cadeb54-a2f5-4d1a-a70f-be3583e3937c.jpg'
      }
    },
    {
      type_of: 'article',
      id: 621341,
      title: 'Distributed Caching in ASP.NET Core with Redis',
      description: 'About a year ago, I wrote a blog post on simple In-Memory Caching in ASP.NET Core with IMemoryCache....',
      readable_publish_date: 'Mar  1',
      slug: 'distributed-caching-in-asp-net-core-with-redis-1io0',
      path: '/sahan/distributed-caching-in-asp-net-core-with-redis-1io0',
      url: 'https://dev.to/sahan/distributed-caching-in-asp-net-core-with-redis-1io0',
      comments_count: 4,
      public_reactions_count: 21,
      collection_id: null,
      published_timestamp: '2021-03-01T11:38:23Z',
      positive_reactions_count: 21,
      cover_image: 'https://res.cloudinary.com/practicaldev/image/fetch/s--6IcgYqex--/c_imagga_scale,f_auto,fl_progressive,h_420,q_auto,w_1000/https://sahansera.dev/static/8d28c5eae05b19aaf2fac0b63ec6a136/fdaa2/distributed-caching-in-aspdotnet-core-with-redis.png',
      social_image: 'https://res.cloudinary.com/practicaldev/image/fetch/s--CfQDE2m6--/c_imagga_scale,f_auto,fl_progressive,h_500,q_auto,w_1000/https://sahansera.dev/static/8d28c5eae05b19aaf2fac0b63ec6a136/fdaa2/distributed-caching-in-aspdotnet-core-with-redis.png',
      canonical_url: 'https://sahansera.dev/distributed-caching-aspnet-core-redis/',
      created_at: '2021-03-01T08:20:12Z',
      edited_at: '2021-03-01T23:23:47Z',
      crossposted_at: '2021-03-01T11:38:23Z',
      published_at: '2021-03-01T11:38:00Z',
      last_comment_at: '2021-03-02T05:31:43Z',
      tag_list: [
        'dotnet',
        'csharp',
        'tutorial'
      ],
      tags: 'dotnet, csharp, tutorial',
      user: {
        name: 'Sahan',
        username: 'sahan',
        twitter_username: 'Sahan91',
        github_username: 'sahan91',
        website_url: 'https://sahansera.dev',
        profile_image: 'https://res.cloudinary.com/practicaldev/image/fetch/s--HWE-tfQm--/c_fill,f_auto,fl_progressive,h_640,q_auto,w_640/https://dev-to-uploads.s3.amazonaws.com/uploads/user/profile_image/222556/4502fb4c-7962-40f9-a1d2-f699e8b5a164.jpeg',
        profile_image_90: 'https://res.cloudinary.com/practicaldev/image/fetch/s--kxyUQadY--/c_fill,f_auto,fl_progressive,h_90,q_auto,w_90/https://dev-to-uploads.s3.amazonaws.com/uploads/user/profile_image/222556/4502fb4c-7962-40f9-a1d2-f699e8b5a164.jpeg'
      }
    },
    {
      type_of: 'article',
      id: 620521,
      title: 'What every ASP.NET Core Web API project needs - Part 2 - API versioning and Swagger',
      description: 'In my previous article, I wrote about adding Serilog to the project and configuring it through the ap...',
      readable_publish_date: 'Mar  1',
      slug: 'what-every-asp-net-core-web-api-project-needs-part-2-api-versioning-and-swagger-3nfm',
      path: '/moesmp/what-every-asp-net-core-web-api-project-needs-part-2-api-versioning-and-swagger-3nfm',
      url: 'https://dev.to/moesmp/what-every-asp-net-core-web-api-project-needs-part-2-api-versioning-and-swagger-3nfm',
      comments_count: 0,
      public_reactions_count: 11,
      collection_id: null,
      published_timestamp: '2021-03-01T15:57:29Z',
      positive_reactions_count: 11,
      cover_image: 'https://res.cloudinary.com/practicaldev/image/fetch/s--qQ_HgnuN--/c_imagga_scale,f_auto,fl_progressive,h_420,q_auto,w_1000/https://dev-to-uploads.s3.amazonaws.com/uploads/articles/a89vxb1i0a6232m755w0.jpg',
      social_image: 'https://res.cloudinary.com/practicaldev/image/fetch/s--v6zADqrP--/c_imagga_scale,f_auto,fl_progressive,h_500,q_auto,w_1000/https://dev-to-uploads.s3.amazonaws.com/uploads/articles/a89vxb1i0a6232m755w0.jpg',
      canonical_url: 'https://dev.to/moesmp/what-every-asp-net-core-web-api-project-needs-part-2-api-versioning-and-swagger-3nfm',
      created_at: '2021-02-28T08:54:39Z',
      edited_at: null,
      crossposted_at: null,
      published_at: '2021-03-01T15:57:29Z',
      last_comment_at: '2021-03-01T15:57:29Z',
      tag_list: [
        'architecture',
        'dotnet',
        'aspnetcore',
        'webapi'
      ],
      tags: 'architecture, dotnet, aspnetcore, webapi',
      user: {
        name: 'Mohsen Esmailpour',
        username: 'moesmp',
        twitter_username: null,
        github_username: 'mo-esmp',
        website_url: null,
        profile_image: 'https://res.cloudinary.com/practicaldev/image/fetch/s--rdKGayYN--/c_fill,f_auto,fl_progressive,h_640,q_auto,w_640/https://dev-to-uploads.s3.amazonaws.com/uploads/user/profile_image/509426/a5802b3b-b845-438e-8387-9fa9cf1e3279.jpg',
        profile_image_90: 'https://res.cloudinary.com/practicaldev/image/fetch/s--FasG_gb1--/c_fill,f_auto,fl_progressive,h_90,q_auto,w_90/https://dev-to-uploads.s3.amazonaws.com/uploads/user/profile_image/509426/a5802b3b-b845-438e-8387-9fa9cf1e3279.jpg'
      }
    },
    {
      type_of: 'article',
      id: 621657,
      title: 'When Alternatives are Unhelpful: A Ruby Case Study',
      description: "In design (of software and non-software products), is it good to provide several alternatives? Let's...",
      readable_publish_date: 'Mar  1',
      slug: 'when-alternatives-are-unhelpful-a-ruby-case-study-2m85',
      path: '/shalvah/when-alternatives-are-unhelpful-a-ruby-case-study-2m85',
      url: 'https://dev.to/shalvah/when-alternatives-are-unhelpful-a-ruby-case-study-2m85',
      comments_count: 0,
      public_reactions_count: 4,
      collection_id: null,
      published_timestamp: '2021-03-01T13:46:32Z',
      positive_reactions_count: 4,
      cover_image: null,
      social_image: 'https://dev.to/social_previews/article/621657.png',
      canonical_url: 'https://blog.shalvah.me/posts/when-alternatives-are-unhelpful-a-ruby-case-study-83bcd767-a31b-47da-ac7a-05ad5471cad7',
      created_at: '2021-03-01T13:46:32Z',
      edited_at: '2021-03-01T14:07:50Z',
      crossposted_at: null,
      published_at: '2021-03-01T13:46:32Z',
      last_comment_at: '2021-03-01T13:46:32Z',
      tag_list: [
        'ruby'
      ],
      tags: 'ruby',
      user: {
        name: 'Shalvah',
        username: 'shalvah',
        twitter_username: 'theshalvah',
        github_username: 'shalvah',
        website_url: 'http://shalvah.me',
        profile_image: 'https://res.cloudinary.com/practicaldev/image/fetch/s--yL1qLAbf--/c_fill,f_auto,fl_progressive,h_640,q_auto,w_640/https://dev-to-uploads.s3.amazonaws.com/uploads/user/profile_image/52230/87936f32-1b89-4d87-97af-09dfe698930d.jpg',
        profile_image_90: 'https://res.cloudinary.com/practicaldev/image/fetch/s--KFgszYAi--/c_fill,f_auto,fl_progressive,h_90,q_auto,w_90/https://dev-to-uploads.s3.amazonaws.com/uploads/user/profile_image/52230/87936f32-1b89-4d87-97af-09dfe698930d.jpg'
      }
    },
    {
      type_of: 'article',
      id: 621019,
      title: 'Re-writing then/catch to async/await',
      description: 'There are two main ways to handle asynchronous code in JavaScript:    then/catch (ES6), and  async/aw...',
      readable_publish_date: 'Feb 28',
      slug: 're-writing-then-catch-to-async-await-2l02',
      path: '/gladyspascual/re-writing-then-catch-to-async-await-2l02',
      url: 'https://dev.to/gladyspascual/re-writing-then-catch-to-async-await-2l02',
      comments_count: 3,
      public_reactions_count: 11,
      collection_id: null,
      published_timestamp: '2021-02-28T23:19:48Z',
      positive_reactions_count: 11,
      cover_image: 'https://res.cloudinary.com/practicaldev/image/fetch/s--fjno1w3N--/c_imagga_scale,f_auto,fl_progressive,h_420,q_auto,w_1000/https://dev-to-uploads.s3.amazonaws.com/uploads/articles/8cq5xt60n56l19qkruzn.jpg',
      social_image: 'https://res.cloudinary.com/practicaldev/image/fetch/s--chfXzWQ6--/c_imagga_scale,f_auto,fl_progressive,h_500,q_auto,w_1000/https://dev-to-uploads.s3.amazonaws.com/uploads/articles/8cq5xt60n56l19qkruzn.jpg',
      canonical_url: 'https://dev.to/gladyspascual/re-writing-then-catch-to-async-await-2l02',
      created_at: '2021-02-28T23:19:48Z',
      edited_at: '2021-03-01T20:12:58Z',
      crossposted_at: null,
      published_at: '2021-02-28T23:19:48Z',
      last_comment_at: '2021-03-01T20:37:49Z',
      tag_list: [
        'javascript',
        'beginners'
      ],
      tags: 'javascript, beginners',
      user: {
        name: 'Gladys Pascual',
        username: 'gladyspascual',
        twitter_username: null,
        github_username: 'gladys-pascual',
        website_url: 'https://www.gladyspascual.me/',
        profile_image: 'https://res.cloudinary.com/practicaldev/image/fetch/s--QBPzjgvt--/c_fill,f_auto,fl_progressive,h_640,q_auto,w_640/https://dev-to-uploads.s3.amazonaws.com/uploads/user/profile_image/413143/d7cfec38-92e2-44bc-95b1-22b91f73eb7a.jpg',
        profile_image_90: 'https://res.cloudinary.com/practicaldev/image/fetch/s--Vlx_c9ql--/c_fill,f_auto,fl_progressive,h_90,q_auto,w_90/https://dev-to-uploads.s3.amazonaws.com/uploads/user/profile_image/413143/d7cfec38-92e2-44bc-95b1-22b91f73eb7a.jpg'
      }
    },
    {
      type_of: 'article',
      id: 621088,
      title: 'Share variables between JavaScript and CSS',
      description: 'Whether you need site breakpoints for matchMedia or access to theme colors, sharing values between yo...',
      readable_publish_date: 'Mar  1',
      slug: 'share-variables-between-javascript-and-css-5ad0',
      path: '/falldowngoboone/share-variables-between-javascript-and-css-5ad0',
      url: 'https://dev.to/falldowngoboone/share-variables-between-javascript-and-css-5ad0',
      comments_count: 1,
      public_reactions_count: 10,
      collection_id: null,
      published_timestamp: '2021-03-01T02:16:29Z',
      positive_reactions_count: 10,
      cover_image: null,
      social_image: 'https://dev.to/social_previews/article/621088.png',
      canonical_url: 'https://www.falldowngoboone.com/blog/share-variables-between-javascript-and-css/',
      created_at: '2021-03-01T02:16:29Z',
      edited_at: null,
      crossposted_at: null,
      published_at: '2021-03-01T02:16:29Z',
      last_comment_at: '2021-03-01T09:51:12Z',
      tag_list: [
        'javascript',
        'css',
        'sass'
      ],
      tags: 'javascript, css, sass',
      user: {
        name: 'Ryan Boone',
        username: 'falldowngoboone',
        twitter_username: 'therealboone',
        github_username: 'falldowngoboone',
        website_url: 'https://www.falldowngoboone.com',
        profile_image: 'https://res.cloudinary.com/practicaldev/image/fetch/s--fcbDo9pX--/c_fill,f_auto,fl_progressive,h_640,q_auto,w_640/https://dev-to-uploads.s3.amazonaws.com/uploads/user/profile_image/295770/a76b127d-1218-4a5c-b6d5-f03be7143e18.png',
        profile_image_90: 'https://res.cloudinary.com/practicaldev/image/fetch/s--w7sbdaqU--/c_fill,f_auto,fl_progressive,h_90,q_auto,w_90/https://dev-to-uploads.s3.amazonaws.com/uploads/user/profile_image/295770/a76b127d-1218-4a5c-b6d5-f03be7143e18.png'
      }
    },
    {
      type_of: 'article',
      id: 619986,
      title: 'Ruby on Rails + Auth0: Authenticating your API with an external authentication service',
      description: 'Introduction   In 2019 I wrote a post with this same subject and an extra tool: Knock.   Wit...',
      readable_publish_date: 'Mar  1',
      slug: 'ruby-on-rails-auth0-authenticating-your-api-with-an-external-authentication-service-99b',
      path: '/rwehresmann/ruby-on-rails-auth0-authenticating-your-api-with-an-external-authentication-service-99b',
      url: 'https://dev.to/rwehresmann/ruby-on-rails-auth0-authenticating-your-api-with-an-external-authentication-service-99b',
      comments_count: 0,
      public_reactions_count: 5,
      collection_id: null,
      published_timestamp: '2021-03-01T01:30:44Z',
      positive_reactions_count: 5,
      cover_image: 'https://res.cloudinary.com/practicaldev/image/fetch/s--Nm294zPT--/c_imagga_scale,f_auto,fl_progressive,h_420,q_auto,w_1000/https://dev-to-uploads.s3.amazonaws.com/uploads/articles/nsl4o20kwepq9bmhngag.png',
      social_image: 'https://res.cloudinary.com/practicaldev/image/fetch/s--YIrTB0dn--/c_imagga_scale,f_auto,fl_progressive,h_500,q_auto,w_1000/https://dev-to-uploads.s3.amazonaws.com/uploads/articles/nsl4o20kwepq9bmhngag.png',
      canonical_url: 'https://dev.to/rwehresmann/ruby-on-rails-auth0-authenticating-your-api-with-an-external-authentication-service-99b',
      created_at: '2021-02-27T14:37:37Z',
      edited_at: null,
      crossposted_at: null,
      published_at: '2021-03-01T01:30:44Z',
      last_comment_at: '2021-03-01T01:30:44Z',
      tag_list: [
        'ruby',
        'auth0',
        'api',
        'authentication'
      ],
      tags: 'ruby, auth0, api, authentication',
      user: {
        name: 'Rodrigo Walter Ehresmann',
        username: 'rwehresmann',
        twitter_username: 'rwehresmann',
        github_username: 'rwehresmann',
        website_url: 'https://github.com/rwehresmann',
        profile_image: 'https://res.cloudinary.com/practicaldev/image/fetch/s--ilGXX6kj--/c_fill,f_auto,fl_progressive,h_640,q_auto,w_640/https://dev-to-uploads.s3.amazonaws.com/uploads/user/profile_image/580586/2c02379b-a9e2-4340-967c-df8089ffc942.jpeg',
        profile_image_90: 'https://res.cloudinary.com/practicaldev/image/fetch/s--MGQVgRCO--/c_fill,f_auto,fl_progressive,h_90,q_auto,w_90/https://dev-to-uploads.s3.amazonaws.com/uploads/user/profile_image/580586/2c02379b-a9e2-4340-967c-df8089ffc942.jpeg'
      }
    },
    {
      type_of: 'article',
      id: 620926,
      title: 'Vanilla Javascript Fetch Refresher',
      description: "If you've been developing with any of the powerful Javascript frameworks/libraries like React, Vue, a...",
      readable_publish_date: 'Feb 28',
      slug: 'vanilla-javascript-fetch-refresher-4nbc',
      path: '/terrythreatt/vanilla-javascript-fetch-refresher-4nbc',
      url: 'https://dev.to/terrythreatt/vanilla-javascript-fetch-refresher-4nbc',
      comments_count: 0,
      public_reactions_count: 9,
      collection_id: null,
      published_timestamp: '2021-02-28T21:18:00Z',
      positive_reactions_count: 9,
      cover_image: null,
      social_image: 'https://dev.to/social_previews/article/620926.png',
      canonical_url: 'https://dev.to/terrythreatt/vanilla-javascript-fetch-refresher-4nbc',
      created_at: '2021-02-28T21:18:00Z',
      edited_at: null,
      crossposted_at: null,
      published_at: '2021-02-28T21:18:00Z',
      last_comment_at: '2021-02-28T21:18:00Z',
      tag_list: [
        'javascript',
        'webdev',
        'beginners',
        'react'
      ],
      tags: 'javascript, webdev, beginners, react',
      user: {
        name: 'Terry Threatt',
        username: 'terrythreatt',
        twitter_username: 'manwittaplan',
        github_username: 'TerryThreatt',
        website_url: 'http://www.terrythreatt.com',
        profile_image: 'https://res.cloudinary.com/practicaldev/image/fetch/s--mS1mLuHG--/c_fill,f_auto,fl_progressive,h_640,q_auto,w_640/https://dev-to-uploads.s3.amazonaws.com/uploads/user/profile_image/335897/20a415d7-e2b9-4429-958a-bb401dd230ae.jpeg',
        profile_image_90: 'https://res.cloudinary.com/practicaldev/image/fetch/s--vXfCN7MK--/c_fill,f_auto,fl_progressive,h_90,q_auto,w_90/https://dev-to-uploads.s3.amazonaws.com/uploads/user/profile_image/335897/20a415d7-e2b9-4429-958a-bb401dd230ae.jpeg'
      }
    },
    {
      type_of: 'article',
      id: 621001,
      title: '10 powerful built-in functions from the Python standard library',
      description: 'Photo by Divide By Zero on Unsplash  There are a ton of awesome packages available in the Python ecos...',
      readable_publish_date: 'Feb 28',
      slug: '10-powerful-built-in-functions-from-the-python-standard-library-1116',
      path: '/jmswaney/10-powerful-built-in-functions-from-the-python-standard-library-1116',
      url: 'https://dev.to/jmswaney/10-powerful-built-in-functions-from-the-python-standard-library-1116',
      comments_count: 0,
      public_reactions_count: 5,
      collection_id: null,
      published_timestamp: '2021-02-28T22:26:43Z',
      positive_reactions_count: 5,
      cover_image: 'https://res.cloudinary.com/practicaldev/image/fetch/s--vXbOw7SZ--/c_imagga_scale,f_auto,fl_progressive,h_420,q_auto,w_1000/https://dev-to-uploads.s3.amazonaws.com/uploads/articles/a0sdk0d2gndopmuqfcff.jpg',
      social_image: 'https://res.cloudinary.com/practicaldev/image/fetch/s--UIXNXyEi--/c_imagga_scale,f_auto,fl_progressive,h_500,q_auto,w_1000/https://dev-to-uploads.s3.amazonaws.com/uploads/articles/a0sdk0d2gndopmuqfcff.jpg',
      canonical_url: 'https://blog.jmswaney.com/10-powerful-built-in-functions-from-the-python-standard-library',
      created_at: '2021-02-28T22:26:43Z',
      edited_at: '2021-03-01T02:30:41Z',
      crossposted_at: null,
      published_at: '2021-02-28T22:26:43Z',
      last_comment_at: '2021-02-28T22:26:43Z',
      tag_list: [
        'python',
        'programming'
      ],
      tags: 'python, programming',
      user: {
        name: 'Justin Swaney',
        username: 'jmswaney',
        twitter_username: null,
        github_username: 'jmswaney',
        website_url: 'https://www.jmswaney.com/',
        profile_image: 'https://res.cloudinary.com/practicaldev/image/fetch/s--HUjc1FJ1--/c_fill,f_auto,fl_progressive,h_640,q_auto,w_640/https://dev-to-uploads.s3.amazonaws.com/uploads/user/profile_image/577399/f5aaca52-f8f6-48ec-9c5f-d8575690221e.jpeg',
        profile_image_90: 'https://res.cloudinary.com/practicaldev/image/fetch/s--Y9plyCqT--/c_fill,f_auto,fl_progressive,h_90,q_auto,w_90/https://dev-to-uploads.s3.amazonaws.com/uploads/user/profile_image/577399/f5aaca52-f8f6-48ec-9c5f-d8575690221e.jpeg'
      }
    },
    {
      type_of: 'article',
      id: 617892,
      title: 'Node.JS - Foal framework - Version 2.2 is here',
      description: 'Version 2.2 release notes',
      readable_publish_date: 'Feb 25',
      slug: 'node-js-foal-framework-version-2-2-is-here-55fb',
      path: '/loicpoullain/node-js-foal-framework-version-2-2-is-here-55fb',
      url: 'https://dev.to/loicpoullain/node-js-foal-framework-version-2-2-is-here-55fb',
      comments_count: 0,
      public_reactions_count: 7,
      collection_id: null,
      published_timestamp: '2021-02-25T10:55:35Z',
      positive_reactions_count: 7,
      cover_image: 'https://res.cloudinary.com/practicaldev/image/fetch/s--pmO4eelA--/c_imagga_scale,f_auto,fl_progressive,h_420,q_auto,w_1000/https://foalts.org/assets/images/banner-6265743e69efeb2a40aebb31b003df5c.png',
      social_image: 'https://res.cloudinary.com/practicaldev/image/fetch/s--u9rXQ4Dg--/c_imagga_scale,f_auto,fl_progressive,h_500,q_auto,w_1000/https://foalts.org/assets/images/banner-6265743e69efeb2a40aebb31b003df5c.png',
      canonical_url: 'https://dev.to/loicpoullain/node-js-foal-framework-version-2-2-is-here-55fb',
      created_at: '2021-02-25T10:55:35Z',
      edited_at: null,
      crossposted_at: null,
      published_at: '2021-02-25T10:55:35Z',
      last_comment_at: '2021-02-25T10:55:35Z',
      tag_list: [
        'typescript',
        'javascript',
        'node',
        'webdev'
      ],
      tags: 'typescript, javascript, node, webdev',
      user: {
        name: 'Loïc Poullain',
        username: 'loicpoullain',
        twitter_username: null,
        github_username: 'LoicPoullain',
        website_url: 'https://foalts.org',
        profile_image: 'https://res.cloudinary.com/practicaldev/image/fetch/s--4VgQ1ON7--/c_fill,f_auto,fl_progressive,h_640,q_auto,w_640/https://dev-to-uploads.s3.amazonaws.com/uploads/user/profile_image/109551/1fbc582c-5d7b-41c6-9559-ca88fc95d6d4.png',
        profile_image_90: 'https://res.cloudinary.com/practicaldev/image/fetch/s--NDv7cF5s--/c_fill,f_auto,fl_progressive,h_90,q_auto,w_90/https://dev-to-uploads.s3.amazonaws.com/uploads/user/profile_image/109551/1fbc582c-5d7b-41c6-9559-ca88fc95d6d4.png'
      }
    },
    {
      type_of: 'article',
      id: 620518,
      title: 'Difference between react props vs. state\n',
      description: 'One of the core concepts of react is the difference between props and state. Only changes in props an...',
      readable_publish_date: 'Feb 28',
      slug: 'react-props-vs-state-56l5',
      path: '/code_runner/react-props-vs-state-56l5',
      url: 'https://dev.to/code_runner/react-props-vs-state-56l5',
      comments_count: 4,
      public_reactions_count: 8,
      collection_id: null,
      published_timestamp: '2021-02-28T08:45:23Z',
      positive_reactions_count: 8,
      cover_image: 'https://res.cloudinary.com/practicaldev/image/fetch/s--OTJfk6pe--/c_imagga_scale,f_auto,fl_progressive,h_420,q_auto,w_1000/https://dev-to-uploads.s3.amazonaws.com/uploads/articles/n2yvguakcwj9hcb27jrr.png',
      social_image: 'https://res.cloudinary.com/practicaldev/image/fetch/s--8FEv6T6P--/c_imagga_scale,f_auto,fl_progressive,h_500,q_auto,w_1000/https://dev-to-uploads.s3.amazonaws.com/uploads/articles/n2yvguakcwj9hcb27jrr.png',
      canonical_url: 'https://dev.to/code_runner/react-props-vs-state-56l5',
      created_at: '2021-02-28T08:45:23Z',
      edited_at: '2021-02-28T09:36:47Z',
      crossposted_at: null,
      published_at: '2021-02-28T08:45:23Z',
      last_comment_at: '2021-03-01T06:45:29Z',
      tag_list: [
        'reactnative',
        'javascript',
        'react',
        'programming'
      ],
      tags: 'reactnative, javascript, react, programming',
      user: {
        name: 'Hans',
        username: 'code_runner',
        twitter_username: 'hansodeg',
        github_username: 'hansodeg',
        website_url: null,
        profile_image: 'https://res.cloudinary.com/practicaldev/image/fetch/s--2OPStFX6--/c_fill,f_auto,fl_progressive,h_640,q_auto,w_640/https://dev-to-uploads.s3.amazonaws.com/uploads/user/profile_image/310830/ed158114-dd45-4f1a-a15f-b19d7444e21e.jpeg',
        profile_image_90: 'https://res.cloudinary.com/practicaldev/image/fetch/s--JYZDgdSy--/c_fill,f_auto,fl_progressive,h_90,q_auto,w_90/https://dev-to-uploads.s3.amazonaws.com/uploads/user/profile_image/310830/ed158114-dd45-4f1a-a15f-b19d7444e21e.jpeg'
      }
    },
    {
      type_of: 'article',
      id: 620904,
      title: 'Profiling Python with cProfile, and a speedup tip',
      description: 'We would love for our Python programs to run as fast as possible, but figuring out how to speed thing...',
      readable_publish_date: 'Feb 28',
      slug: 'profiling-python-with-cprofile-and-a-speedup-tip-1bib',
      path: '/wrighter/profiling-python-with-cprofile-and-a-speedup-tip-1bib',
      url: 'https://dev.to/wrighter/profiling-python-with-cprofile-and-a-speedup-tip-1bib',
      comments_count: 0,
      public_reactions_count: 0,
      collection_id: null,
      published_timestamp: '2021-02-28T19:46:25Z',
      positive_reactions_count: 0,
      cover_image: null,
      social_image: 'https://dev.to/social_previews/article/620904.png',
      canonical_url: 'https://www.wrighters.io/profiling-python-with-cprofile-and-a-speedup-tip/',
      created_at: '2021-02-28T19:44:55Z',
      edited_at: null,
      crossposted_at: '2021-02-28T19:46:25Z',
      published_at: '2021-02-18T00:24:18Z',
      last_comment_at: '2021-02-18T00:24:18Z',
      tag_list: [
        'python'
      ],
      tags: 'python',
      user: {
        name: 'wrighter',
        username: 'wrighter',
        twitter_username: null,
        github_username: 'wrighter',
        website_url: 'https://wrighters.io',
        profile_image: 'https://res.cloudinary.com/practicaldev/image/fetch/s--iDQvnsET--/c_fill,f_auto,fl_progressive,h_640,q_auto,w_640/https://dev-to-uploads.s3.amazonaws.com/uploads/user/profile_image/323341/bd59e3ab-8a5e-4fd6-94ae-5b3feed68773.jpeg',
        profile_image_90: 'https://res.cloudinary.com/practicaldev/image/fetch/s--fPAyWxEz--/c_fill,f_auto,fl_progressive,h_90,q_auto,w_90/https://dev-to-uploads.s3.amazonaws.com/uploads/user/profile_image/323341/bd59e3ab-8a5e-4fd6-94ae-5b3feed68773.jpeg'
      }
    }
  ]
}
